#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HttpClient.Android.Resource", IsApplication=true)]

namespace HttpClient.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::HttpClient.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int button1 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int html_textView = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout2 = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int radioButton1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int radioButton2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int radioButton3 = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int radioGroup1 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int select_api = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int textView1 = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ShowStream = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int busy_msg = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int html_returned = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int http_okhttp = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int http_standard = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int http_webreq = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int issue_request = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int no_data = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int select_api = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
